[workspace]
resolver = "3"
members = ["crates/dtam-core", "crates/dtam-video", "crates/dtam-viewer", "crates/dtam-cli"]

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
wgpu = "30"
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.4"
log = "0.4"
nalgebra = "0.35"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
