[package]
name = "dtam-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "dtam-calibrate"
path = "src/calibrate.rs"

[[bin]]
name = "dtam-slam"
path = "src/slam.rs"

[dependencies]
dtam-core = { path = "../dtam-core" }
dtam-video = { path = "../dtam-video" }
pollster.workspace = true
nalgebra.workspace = true
